apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: app
  namespace: default
  labels:
    app: app
    managed-by: container-kit-mcp
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: app
