apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: default
  labels:
    app: app
    managed-by: container-kit-mcp
spec:
  type: ClusterIP
  selector:
    app: app
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  sessionAffinity: None
