id: base-image-resolution
name: AI-Powered Base Image Resolution
description: Intelligently recommend Docker base images based on comprehensive analysis
version: 2.0.0
system: |
  You are a Docker security and performance expert with comprehensive knowledge of:
  - Current CVE landscape and security vulnerabilities
  - Performance characteristics of different base images
  - Ecosystem-specific best practices and recent changes
  - Multi-architecture support and compatibility
  - License compliance and enterprise requirements
  
  Always prioritize security while balancing performance and maintainability.
  Consider the CURRENT DATE when making recommendations (older versions may have vulnerabilities).

user: |
  Based on this repository analysis, recommend the optimal Docker base image:
  
  **Repository Analysis:**
  - Language: {{language}} {{languageVersion}}
  - Framework: {{framework}} {{frameworkVersion}}
  - Dependencies: {{dependencies}}
  - Build System: {{buildSystem}}
  - Production Environment: {{targetEnvironment}}
  
  **Requirements:**
  - Security Level: {{securityLevel}} (minimal/standard/hardened)
  - Performance Priority: {{performancePriority}} (size/speed/memory)
  - Architecture Support: {{architectures}}
  - Compliance Requirements: {{complianceRequirements}}
  
  **Context:**
  - Current Date: {{currentDate}}
  - Target Deployment: {{deploymentType}} (cloud/on-prem/edge)
  - Resource Constraints: {{resourceConstraints}}
  
  **Language-Specific Options** (as reference, but use your expertise to choose the BEST current option):
  {{#if suggestedImages}}
  {{#each suggestedImages}}
  - {{this.category}}: {{this.image}} ({{this.notes}})
  {{/each}}
  {{/if}}
  
  Provide recommendation in JSON format:
  {
    "primary_recommendation": {
      "image": "exact_image_tag",
      "reasoning": "detailed_explanation_of_choice",
      "security_notes": "security_considerations_and_benefits",
      "performance_notes": "performance_characteristics",
      "tradeoffs": "what_you_optimized_for_and_what_you_sacrificed"
    },
    "alternatives": [
      {
        "image": "alternative_image_tag",
        "use_case": "when_to_use_this_instead",
        "pros": ["list_of_advantages"],
        "cons": ["list_of_disadvantages"]
      }
    ],
    "security_considerations": {
      "vulnerability_status": "assessment_of_known_issues",
      "update_frequency": "how_often_base_image_is_updated",
      "compliance": "relevant_compliance_standards_met"
    },
    "optimization_tips": [
      "specific_dockerfile_optimizations_for_this_base_image"
    ],
    "health_check_recommendation": {
      "endpoint": "recommended_health_check_endpoint",
      "command": "recommended_health_check_command"
    }
  }

outputFormat: json
max_tokens: 2000
temperature: 0.1